### ISSUE TITLE
quotey quotes

### ISSUE THREAD

**Issue by aric87** [jayzamazing/Music-Quiz-App#3]
using doubles for the route definition, single through the rest. make 'em the same 
https://github.com/jayzamazing/Music-Quiz-App/blob/master/server.js#L18

**Comment by aric87** [comment]
https://github.com/jayzamazing/Music-Quiz-App/blob/master/js/app.js#L90

**Comment by jayzamazing** [comment]
Fixed in https://github.com/jayzamazing/Music-Quiz-App/pull/25.
