### ISSUE TITLE
use the stored value

### ISSUE THREAD

**Issue by aric87** [jayzamazing/Music-Quiz-App#4]
https://github.com/jayzamazing/Music-Quiz-App/blob/master/js/app.js#L18
You store the value into a variable, then when you call the function, you go back to the DOM to get it again. you should pass in `genreChecked` instead of `$('.genre input:checked').val()`

**Comment by jayzamazing** [comment]
Fixed in https://github.com/jayzamazing/Music-Quiz-App/pull/25.
